import csv
import io
from html import escape


REPORT_COLUMNS = ("S.No", "Furnace", "Melt number", "Shift type", "Total weight (kg)", "Products", "Captured by", "Last captured")


def report_rows(report):
    return [
        [index, item["furnace_name"], item["melt_number"], item["shift_type"],
         f'{item["total_weight"]:.3f}', item["product_count"],
         item["captured_by_username"], item["captured_at"]]
        for index, item in enumerate(report["items"], 1)
    ]


def report_csv(report):
    output = io.StringIO(newline="")
    writer = csv.writer(output, quoting=csv.QUOTE_ALL)
    writer.writerows([
        ["MELT REPORT", "", "", "", "", "", "", ""],
        ["Generated by", report["generated_by"], "Generated on", report["generated_on"], "Shift", report["shift"], "", ""],
        ["From", report["range_from"], "To", report["range_to"], "Furnace", report["furnace"], "", ""],
        [], list(REPORT_COLUMNS),
    ])
    writer.writerows(report_rows(report))
    writer.writerow([])
    writer.writerow(["Grand total", report["total_melts"], "melts", f'{report["total_net_weight"]:.3f} kg', report["total_products"], "products", ""])
    return output.getvalue().encode("utf-8-sig")


def report_pdf(report):
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import LongTable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    output = io.BytesIO()
    document = SimpleDocTemplate(output, pagesize=landscape(A4), leftMargin=30, rightMargin=30, topMargin=32, bottomMargin=32)
    styles = getSampleStyleSheet()
    cell_style = styles["BodyText"].clone("ReportCell")
    cell_style.fontSize = 8
    cell_style.leading = 10
    header_style = cell_style.clone("ReportHeader")
    header_style.textColor = colors.white
    heading = styles["Heading1"].clone("ReportHeading")
    heading.textColor = colors.HexColor("#123a2f")
    value = lambda text: Paragraph(escape(str("-" if text is None or text == "" else text)), cell_style)
    metadata = [
        ["Generated by", report["generated_by"], "Generated on", report["generated_on"]],
        ["From", report["range_from"], "To", report["range_to"]],
        ["Shift", report["shift"], "Furnace", report["furnace"]],
    ]
    meta_table = Table([[value(cell) for cell in row] for row in metadata], colWidths=[90, 210, 90, 210])
    meta_table.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"), ("BOTTOMPADDING", (0, 0), (-1, -1), 7)]))
    rows = [[Paragraph(escape(cell), header_style) for cell in REPORT_COLUMNS]]
    rows.extend([[value(cell) for cell in row] for row in report_rows(report)])
    if len(rows) == 1:
        rows.append([value("No melts match these filters.")] + [""] * 7)
    table = LongTable(rows, colWidths=[32, 96, 85, 75, 85, 65, 100, 180], repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#123a2f")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), .3, colors.HexColor("#c9d8d1")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    if not report["items"]:
        table.setStyle(TableStyle([("SPAN", (0, 1), (-1, 1))]))
    total = f'{report["total_melts"]} melts  |  {report["total_products"]} products  |  {report["total_net_weight"]:.3f} kg'
    story = [Paragraph("Melt Report", heading), Spacer(1, 8), meta_table, Spacer(1, 12), table,
             Spacer(1, 12), Paragraph(escape(total), styles["Heading3"])]

    def footer(canvas, doc):
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#52665e"))
        canvas.drawRightString(landscape(A4)[0] - 30, 18, f"Page {doc.page}")

    document.build(story, onFirstPage=footer, onLaterPages=footer)
    return output.getvalue()
